### ISSUE TITLE
Some minor weird things I noticed

### ISSUE THREAD

**Issue by Butanium** [epfl-dlab/llm-latent-language#1]
- The output format of this one seems weird: https://github.com/epfl-dlab/llm-latent-language/blob/1be3cd6eaf14c7408e8f03703d1c1905a6b00c44/Translation.ipynb#L242
E.g. some column are called "de" but contains french words. 
- This line should use `lang_latent` and not `'en'`: https://github.com/epfl-dlab/llm-latent-language/blob/1be3cd6eaf14c7408e8f03703d1c1905a6b00c44/Translation.ipynb#L316

**Comment by wendlerc** [comment]
Right! Can you make a pull request? 

The `df_en_de_fr` and its column names not matching the actual languages stem from the fact that we started with de and fr and then since the code is the same for other languages just replace the 'de' with the source language and 'fr' with the target language (or the other way around, not sure anymore).
